version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -U -r requirements.txt
      - run:
          name: Run tests
          command: pytest -v tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
